[package]
name = "sample_create_window_sys"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows-sys]
workspace = true
features = [
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
]

[lints]
workspace = true
