[package]
name = "sample_message_box"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
workspace = true
features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
]

[lints]
workspace = true
