[package]
name = "test_winrt"
version = "0.0.0"
authors = ["Microsoft"]
edition = "2018"

[dependencies]
windows = { path = "../../../libs/windows", features = ["alloc"] }
reader = { package = "windows_reader", path = "../../../../crates/libs/reader" }

[dev-dependencies]
futures = "0.3"
helpers = { package = "test_helpers", path = "../helpers" }
