[package]
name = "sample_credentials"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
workspace = true
features = [
    "Win32_Security_Credentials"
]

[lints]
workspace = true
