[package]
name = "overlapped"
version = "0.6.0"
authors = ["Kenny Kerr <kenny.kerr@microsoft.com>"]
edition = "2018"

[dependencies]
bindings = { package = "overlapped_bindings", path = "bindings" }
windows = { path = "../.." }
