pr: ["master"]

jobs:
  - job:
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: ./.ci/install-rust.yml
        parameters:
          rust_version: stable

      - bash: |
          set -ex
          export RUST_BACKTRACE=1
          cargo fmt --all -- --check
          RUSTFLAGS="-D warnings" cargo check --all
          cargo test --all
