[workspace]
resolver = "2"
members = [
    "crates/libs/*",
    "crates/samples/windows-sys/*",
    "crates/samples/windows/*",
    "crates/samples/components/*",
    "crates/targets/*",
    "crates/tests/*",
    "crates/tools/*",
]
exclude = [
    "crates/targets/baseline",
]

[workspace.lints.rust]
rust_2018_idioms = { level = "warn", priority = -1 }
missing_docs = "warn"
unexpected_cfgs = { level = "warn" }
