
[workspace]
members = [
    "crates/libs/*",
    "crates/targets/*",
    "crates/tools/*",
    "crates/tests/legacy/*",
    "crates/tests/metadata/*",
    "crates/tests/winrt/*",
    "crates/tests/win32/*",
    "crates/tests/core",
    "crates/tests/sys",
]
exclude = ["crates/tests/component"]
