[package]
name = "winrt"
version = "0.7.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT"
description = "Windows Runtime language projection"
repository = "https://github.com/microsoft/winrt-rs"
documentation = "https://docs.rs/winrt"
readme = "README.md"

[dependencies]
winrt_macros = { path = "crates/macros",  version = "0.7" }
sha1 = "0.6.0"

[dev-dependencies]
doc-comment = "0.3"

[workspace]
members = [
    "crates/*",
]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc", "i686-pc-windows-msvc"]

[package.metadata.winrt.dependencies]
"Microsoft.Windows.SDK.Contracts" = "10.0.19041.1"
"KennyKerr.Windows.TestWinRT" = "1.0.10"
