[package]
name = "windows"
version = "0.21.1"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust for Windows"
repository = "https://github.com/microsoft/windows-rs"
documentation = "https://docs.rs/windows"
readme = ".github/readme.md"
exclude = [".github", ".windows", "docs", "tests"]

[dependencies]
windows_macros = { path = "crates/macros",  version = "0.21.1", optional = true }
windows_reader = { path = "crates/reader", version = "0.21.1", optional = true }
gen = { package = "windows_gen", path = "crates/gen",  version = "0.21.1", optional = true }

[workspace]
members = ["crates/*", "tests/legacy/*", "tests/metadata/*", "tests/winrt/*", "tests/win32/*"]
exclude = ["tests/component"]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc"]

[features]
default = ["macros"]
macros = ["gen", "windows_macros", "windows_reader"]
raw_dylib = ["gen/raw_dylib"] # TODO: remove feature once raw-dylib has stablized
