[package]
name = "windows"
version = "0.17.2"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust for Windows"
repository = "https://github.com/microsoft/windows-rs"
documentation = "https://docs.rs/windows"
readme = ".github/readme.md"
exclude = [".github", "docs"]

[dependencies]
windows_macros = { path = "crates/macros",  version = "0.17.2", optional = true }
gen = { package = "windows_gen", path = "crates/gen",  version = "0.17.2", optional = true }
const-sha1 = "0.2"

[dev-dependencies]
gen = { package = "windows_gen", path = "crates/gen" }

[workspace]
members = [
    "crates/*",
    "tests/*",
]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc"]

[features]
default = ["macros"]
macros = ["gen", "windows_macros"]
raw_dylib = ["gen/raw_dylib"] # TODO: remove feature once raw-dylib has stablized
