[package]
name = "windows"
version = "0.14.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust for Windows"
repository = "https://github.com/microsoft/windows-rs"
documentation = "https://docs.rs/windows"
readme = "README.md"
exclude = [".github", "docs"]

[dependencies]
windows_macros = { path = "crates/macros",  version = "0.14.0", optional = true }
gen = { package = "windows_gen", path = "crates/gen",  version = "0.14.0", optional = true }
const-sha1 = "0.2"

[dev-dependencies]
gen = { package = "windows_gen", path = "crates/gen" }

[workspace]
members = [
    "crates/*",
    "tests/*",
]

[features]
default = ["macros"]
macros = ["gen", "windows_macros"]
