[workspace]
resolver = "2"
members = [
    "crates/libs/*",
    "crates/samples/windows-sys/*",
    "crates/samples/windows/*",
    "crates/targets/*",
    "crates/tests/*",
    "crates/tools/*",
]
exclude = [
    "crates/targets/baseline",
]

[workspace.lints.rust]
rust_2018_idioms = "warn"
unused_qualifications = "warn"