[package]
name = "winrt"
version = "0.8.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT"
description = "Windows Runtime language projection"
repository = "https://github.com/microsoft/winrt-rs"
documentation = "https://docs.rs/winrt"
readme = "README.md"

[dependencies]
winrt-macros = { path = "crates/macros",  version = "0.8.0" }
winrt-gen = { path = "crates/gen",  version = "0.8.0" }
const-sha1 = "0.2"
winmd = { path = "crates/winmd",  version = "0.8.0" }

[build-dependencies]
winrt-macros = { path = "crates/macros",  version = "0.8.0" }

[dev-dependencies]
doc-comment = "0.3"
winrt-gen = { path = "crates/gen" }

[workspace]
members = [
    "crates/*",
    "examples/*",
]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc", "i686-pc-windows-msvc"]
