[workspace]
resolver = "2"
members = [
    "crates/libs/*",
    "crates/samples/windows-sys/*",
    "crates/samples/windows/*",
    "crates/samples/components/*",
    "crates/targets/*",
    "crates/tests/misc/*",
    "crates/tests/winrt/*",
    "crates/tests/libs/*",
    "crates/tools/*",
]
exclude = [
    "crates/targets/baseline",
]

# This compiles external dependencies (outside crates) with full optimization.
# This can improve run time while iterating on development (testing, etc.).
# This has NO EFFECT on end users using windows-* crates.
[profile.dev.package."*"]
opt-level = 2

[workspace.lints.rust]
rust_2018_idioms = { level = "warn", priority = -1 }
missing_docs = "warn"
unsafe_op_in_unsafe_fn = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(windows_raw_dylib, windows_debugger_visualizer, windows_slim_errors)'] }

[workspace.dependencies]
cppwinrt = { path = "crates/libs/cppwinrt" }
windows = { path = "crates/libs/windows" }
windows-bindgen = { path = "crates/libs/bindgen" }
windows-collections = { path = "crates/libs/collections" }
windows-core = { path = "crates/libs/core" }
windows-future = { path = "crates/libs/future" }
windows-link = { path = "crates/libs/link" }
windows-numerics = { path = "crates/libs/numerics" }
windows-registry = { path = "crates/libs/registry" }
windows-result = { path = "crates/libs/result" }
windows-strings = { path = "crates/libs/strings" }
windows-sys = { path = "crates/libs/sys" }
windows-targets = { path = "crates/libs/targets" }
windows-version = { path = "crates/libs/version" }
helpers = { path = "crates/libs/helpers" }
