[package]
name = "sample_shell"

edition = "2021"
publish = false

[dependencies.windows]
path = "../../../libs/windows"
features = [
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
]
