[package]
name = "sample_counter_sys"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows-sys]
workspace = true
features = [
    "Win32_System_Performance",
]

[lints]
workspace = true
