[package]
name = "sample_component_json_validator_winrt"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "sample"
crate-type = ["cdylib"]

[dependencies]
jsonschema = { version = "0.20", default-features = false }
serde_json = {version = "1.0", default-features = false }

[dependencies.windows]
workspace = true
features = [
    "implement",
    "Win32_System_WinRT",
]

[dependencies.windows-core]
workspace = true

[build-dependencies.windows-bindgen]
workspace = true
