[package]
name = "sample_message_box"
version = "0.0.0"
edition = "2021"

[dependencies.windows]
path = "../../libs/windows"
features = [
    "alloc",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
]
