[package]
name = "spellchecker"
version = "0.0.0"
edition = "2018"

[dependencies.windows]
path = "../../libs/windows"
features = [
    "alloc",
    "Win32_System_Com",
    "Win32_Foundation",
    "Win32_Globalization",
]
