[package]
name = "windows_i686_msvc"
version = "0.53.0"
authors = ["Microsoft"]
edition = "2021"
rust-version = "1.60"
license = "MIT OR Apache-2.0"
description = "Import lib for Windows"
repository = "https://github.com/microsoft/windows-rs"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = []
