[package]
name = "sample_json_validator_winrt_client"
version = "0.0.0"
edition = "2021"
publish = false

[dev-dependencies]
windows-core = { workspace = true }
windows = { workspace = true, features = ["Win32_Foundation"] }

[build-dependencies]
windows-bindgen = { workspace = true }

[dependencies]
sample_json_validator_winrt = { path = "../json_validator_winrt" }

[lints]
workspace = true
