[package]
name = "kernel_event"
version = "0.0.0"
edition = "2018"

[dependencies.windows]
path = "../../libs/windows"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
]
