[package]
name = "sample_service_thread"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
windows-services = { workspace = true }
windows-threading = { workspace = true }

[dependencies.windows-sys]
workspace = true
features = [
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Services",
]

[lints]
workspace = true
