[package]
name = "sample_ocr"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
futures = "0.3.5"

[dependencies.windows]
path = "../../../libs/windows"
features = [
    "Media_Ocr", 
    "Graphics_Imaging", 
    "Storage_Streams", 
    "Foundation",
]
