[package]
name = "sample_ocr"

edition = "2021"
publish = false

[dependencies]
futures = "0.3.5"

[dependencies.windows]
path = "../../../libs/windows"
features = [
    "Media_Ocr", 
    "Graphics_Imaging", 
    "Storage_Streams", 
]
