[package]
name = "sample_ocr"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
workspace = true
features = [
    "Media_Ocr",
    "Graphics_Imaging",
    "Storage_Streams",
]

[lints]
workspace = true
