[package]
name = "sample_overlapped"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
workspace = true
features = [
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Threading",
    "Win32_System_IO",
]

[lints]
workspace = true
