[package]
name = "helpers"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
windows-link = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = "0.9"

[lints]
workspace = true
