[package]
name = "rss"
version = "0.6.1"
authors = ["Kenny Kerr <kenny.kerr@microsoft.com>"]
edition = "2018"

[dependencies]
bindings = { package = "rss_bindings", path = "bindings" }
windows = { path = "../.." }
