[package]
name = "sample_rss"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
workspace = true
features = [
    "std",
    "Web_Syndication",
]

[dependencies]
futures = "0.3"

[lints]
workspace = true
