[package]
name = "sample_thread_pool_work"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
workspace = true
features = [
    "Win32_System_Threading",
]

[lints]
workspace = true
