[package]
name = "sample_thread_pool_work"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.windows]
path = "../../../libs/windows"
features = [
    "Win32_Foundation",
    "Win32_System_Threading",
]
