[package]
name = "sample_core_app"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
workspace = true
features = [
    "ApplicationModel_Core",
    "UI_Core",
    "Win32_Storage_Packaging_Appx",
    "Win32_System_Com",
    "Win32_UI_WindowsAndMessaging"
]

[dependencies.windows-core]
workspace = true

[lints]
workspace = true
