[package]
name = "sample_bits"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
workspace = true
features = [
    "Win32_System_Com",
    "Win32_Networking_BackgroundIntelligentTransferService",
]

[dependencies.windows-core]
workspace = true

[lints]
workspace = true
