[package]
name = "sample_delay_load"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
workspace = true
features = [
    "Win32_System_LibraryLoader",
]

[lints]
workspace = true
