[package]
name = "windows_api2"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
reader = { package = "windows_reader", path = "../../deps/reader", version = "0.28.0" }
gen2 = { package = "windows_gen2", path = "../../deps/gen2", version = "0.28.0" }
rayon = "1.5.1"
