[package]
name = "ocr_bindings"
version = "0.6.1"
authors = ["Kenny Kerr <kenny.kerr@microsoft.com>"]
edition = "2018"

[dependencies]
windows = { path = "../../.." }

[build-dependencies]
windows = { path = "../../.." }
