[package]
name = "overlapped_bindings"
version = "0.9.0"
authors = ["Microsoft"]
edition = "2018"

[dependencies]
windows = { path = "../../.." }

[build-dependencies]
windows = { path = "../../.." }
