[build]
rustflags = [
    # "-D", "warnings",

    # "--cfg", "windows_debugger_visualizer",
    # "--cfg", "windows_raw_dylib",
    # "--cfg", "windows_slim_errors",
    # "-C", "target-feature=+crt-static",
]
