[package]
name = "tool_windows"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
metadata = { package = "windows-metadata", path = "../../libs/metadata", version = "0.34.0" }
bindgen = { package = "windows-bindgen", path = "../../libs/bindgen", version = "0.34.0" }
rayon = "1.5.1"
