[package]
name = "windows_api"
version = "0.21.1"
edition = "2018"
publish = false

[dependencies]
reader = { package = "windows_reader", path = "../reader", version = "0.21.1" }
gen = { package = "windows_gen", path = "../gen", version = "0.21.1" }
rayon = "1.5"
