[package]
name = "ocr"
version = "0.6.1"
authors = ["Kenny Kerr <kenny.kerr@microsoft.com>"]
edition = "2018"

[dependencies]
bindings = { package = "ocr_bindings", path = "bindings" }
windows = { path = "../.." }
futures = "0.3.5"
