[package]
name = "sample_memory_buffer"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
workspace = true
features = [
    "Foundation",
    "Win32_System_WinRT",
]

[lints]
workspace = true
