[package]
name = "clock"
version = "0.4.0"
authors = ["Kenny Kerr <kenny.kerr@microsoft.com>"]
edition = "2018"

[dependencies]
bindings = { package = "clock_bindings", path = "bindings" }
windows = { path = "../.." }
