[package]
name = "sample_task_dialog"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
workspace = true
features = [
    "Win32_UI_Controls",
    "Win32_UI_WindowsAndMessaging",
]

[lints]
workspace = true
