[package]
name = "sample_message_box_sys"
version = "0.0.0"
edition = "2018"

[dependencies.windows-sys]
path = "../../libs/sys"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
]

[features]
default = []
raw_dylib = ["windows-sys/raw_dylib"]
