[package]
name = "windows_gen"
version = "0.3.1"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Code generation for the windows crate"

[dependencies]
windows_gen_macros = { path = "macros",  version = "0.3.1" }
windows_winmd = { path = "../winmd",  version = "0.3.1" }
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"
squote = "0.1.2"
