[package]
name = "winrt-gen"
version = "0.8.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT"
description = "Code generation for the winrt crate"

[dependencies]
winrt-gen-macros = { path = "macros",  version = "0.8.0" }
winmd = { path = "../winmd",  version = "0.8.0" }
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"
squote = "0.1.2"
sha1 = "0.6.0"
rayon = "1.3"
