[package]
name = "sample_device_watcher"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
workspace = true
features = [
    "Devices_Enumeration",
]

[lints]
workspace = true
