[package]
name = "sample_ocr"
version = "0.0.0"
edition = "2021"

[dependencies]
futures = "0.3.5"

[dependencies.windows]
path = "../../libs/windows"
features = [
    "alloc",
    "Media_Ocr", 
    "Graphics_Imaging", 
    "Storage_Streams", 
    "Foundation",
]
