[package]
name = "sample_device_watcher"
version = "0.0.0"
edition = "2018"

[dependencies.windows]
path = "../../libs/windows"
features = [
    "Devices_Enumeration",
    "Foundation_Collections",
]
