[package]
name = "windows_aarch64_gnullvm"
version = "0.48.5"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Import lib for Windows"
repository = "https://github.com/microsoft/windows-rs"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = []
