[package]
name = "sample_wmi"

edition = "2021"
publish = false

[dependencies.windows]
path = "../../../libs/windows"
features = [
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_System_Wmi",
    "Win32_System_Rpc",
    "Win32_Security",
    "Win32_System_Variant",
]
