[package]
name = "sample_consent"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
workspace = true
features = [
    "Security_Credentials_UI",
    "Win32_System_WinRT",
]

[dependencies.windows-future]
workspace = true

[lints]
workspace = true
