[package]
name = "sample_consent"
version = "0.0.0"
edition = "2018"

[dependencies.windows]
path = "../../../libs/windows"
default-features = false
features = [
    "Foundation",
    "Security_Credentials_UI",
    "Win32_Foundation",
    "Win32_System_WinRT",
]
