name: miri

permissions:
  contents: read

on:
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/web.yml'
      - 'crates/libs/rdl/rdl.md'
      - 'web/**'
  push:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/web.yml'
      - 'crates/libs/rdl/rdl.md'
      - 'web/**'
    branches:
      - master

jobs:
  miri:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Update toolchain
        run: rustup update --no-self-update nightly && rustup default nightly-x86_64-pc-windows-msvc
      - name: Add toolchain target
        run: rustup target add x86_64-pc-windows-msvc
      - name: Add miri
        run: rustup toolchain install nightly --component miri
      - name: Check string literals
        run:  cargo miri test -p test_strings --test literals