name: msrv

on:
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/web.yml'
      - 'web/**'
  push:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/web.yml'
      - 'web/**'
    branches:
      - master

jobs:
  msrv:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Rust version
        run: rustup update --no-self-update 1.74 && rustup default 1.74
      - name: Check cppwinrt
        run:  cargo check -p cppwinrt --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.82 && rustup default 1.82
      - name: Check windows
        run:  cargo check -p windows --features Globalization,Win32_Graphics_Direct2D
      - name: Rust version
        run: rustup update --no-self-update 1.82 && rustup default 1.82
      - name: Check windows-bindgen
        run:  cargo check -p windows-bindgen --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.82 && rustup default 1.82
      - name: Check windows-collections
        run:  cargo check -p windows-collections --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.82 && rustup default 1.82
      - name: Check windows-core
        run:  cargo check -p windows-core --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.82 && rustup default 1.82
      - name: Check windows-future
        run:  cargo check -p windows-future --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.74 && rustup default 1.74
      - name: Check windows-implement
        run:  cargo check -p windows-implement --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.74 && rustup default 1.74
      - name: Check windows-interface
        run:  cargo check -p windows-interface --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.71 && rustup default 1.71
      - name: Check windows-link
        run:  cargo check -p windows-link --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.82 && rustup default 1.82
      - name: Check windows-metadata
        run:  cargo check -p windows-metadata --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.82 && rustup default 1.82
      - name: Check windows-numerics
        run:  cargo check -p windows-numerics --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.82 && rustup default 1.82
      - name: Check windows-registry
        run:  cargo check -p windows-registry --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.82 && rustup default 1.82
      - name: Check windows-result
        run:  cargo check -p windows-result --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.82 && rustup default 1.82
      - name: Check windows-services
        run:  cargo check -p windows-services --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.82 && rustup default 1.82
      - name: Check windows-strings
        run:  cargo check -p windows-strings --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.71 && rustup default 1.71
      - name: Check windows-sys
        run:  cargo check -p windows-sys --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.60 && rustup default 1.60
      - name: Check windows-targets
        run:  cargo check -p windows-targets --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.82 && rustup default 1.82
      - name: Check windows-threading
        run:  cargo check -p windows-threading --all-features
      - name: Rust version
        run: rustup update --no-self-update 1.74 && rustup default 1.74
      - name: Check windows-version
        run:  cargo check -p windows-version --all-features