[package]
name = "riddle"
version = "0.2.0"
authors = ["Microsoft"]
edition = "2021"
rust-version = "1.60"
license = "MIT OR Apache-2.0"
description = "Windows metadata compiler"
repository = "https://github.com/microsoft/windows-rs"
readme = "readme.md"

[dependencies.windows-bindgen]
path = "../../libs/bindgen"
version = "0.54.0"
default-features = false
