[package]
name = "riddle"
version = "0.0.1"
authors = ["Microsoft"]
edition = "2021"
rust-version = "1.56"
license = "MIT OR Apache-2.0"
description = "Windows metadata compiler"
repository = "https://github.com/microsoft/windows-rs"

[dependencies.windows-bindgen]
path = "../../libs/bindgen"
version = "0.52.0"
default-features = false
