[package]
name = "sample_component_json_validator"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
jsonschema = "0.17"
serde_json = "1.0"

[dependencies.windows]
path = "../../../libs/windows"
features = [
    "Win32_Foundation",
]
