[package]
name = "sample_json_validator"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
jsonschema = { version = "0.23", default-features = false }
serde_json = { workspace = true }
windows = { workspace = true, features = ["Win32_System_Com"] }

[lints]
workspace = true
